# Image Input/Output
# ----------------------------------------------------------------------------------------------
in_channels : 3
num_classes : 2

# Training
# ----------------------------------------------------------------------------------------------
# unet, linknet
model_name : linknet
batch_size : 4
epochs : 2000
learning_rate : !!float 3e-4
val_plot_epoch : 1
augment : False
transfer_lr : False
gpu : !!str 2

# Experiment Setup
# ----------------------------------------------------------------------------------------------
experiment : patchify

# Patchify (phr & phr_cb experiment)
# ----------------------------------------------------------------------------------------------
patchify : True
patch_class_balance : False # whether not to use class balance while doing patchify
patch_size : 512 # height = width, anyone is suitable
stride : 512
p_train_dir : json/train_patch_512.json
p_valid_dir : json/val_patch_512.json
p_test_dir : json/test_patch_512.json

# Dataset
# ----------------------------------------------------------------------------------------------
weights : False # False if cfr, True if cfr_cb
balance_weights : [1.4, 8.6] # cfr_cb experiment
dataset_dir : D:/MsCourse/AI/project/flood_detection/pytorch/data/
root_dir : D:/MsCourse/AI/project/flood_detection/tensorflow
train_size : 0.8
train_dir : train.csv
valid_dir : valid.csv
test_dir : test.csv

# Logger/Callbacks
# ----------------------------------------------------------------------------------------------
csv : True
val_pred_plot : True
lr : True
tensorboard : True
early_stop : True
checkpoint : True
patience : 300 # required for early_stopping, if accuracy does not change for 500 epochs, model will stop automatically

# Evaluation
# ----------------------------------------------------------------------------------------------
load_model_name : linknet_ex_patchify_epochs_2000_28-May-23.hdf5
load_model_dir : None

# Prediction Plot
# ----------------------------------------------------------------------------------------------
plot_single : True # if True, then only index x_test image will plot
index : -1 # by default -1 means random image else specific index image provide by user